### Questions 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
np.arange(start=2, stop=53, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

### Questions 2: Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
A=[]
B=[]

for i in range(5):
    number1 = int(input(''))
    A.append(number1)
print("List 1 :",A,'\n')

for j in range(5):
    number2 = int(input())
    B.append(number2)
print("List 2 :",B,'\n')

List1=np.array(A)                                         # Converting List to Array
print("Array List1 :",List1)

List2=np.array(B)                                         # Converting List to Array
print("Array List2 :",List2)

Concatenation_Array=np.concatenate((A,B))                 # Concatenation of Arrays
print("Concatenation Array :",Concatenation_Array)

Sorted_Array=np.sort(Concatenation_Array)                 # Sorting of Array
print("Sorted Array :",Sorted_Array)

11
12
32
56
45
List 1 : [11, 12, 32, 56, 45] 

77
98
87
95
46
List 2 : [77, 98, 87, 95, 46] 

Array List1 : [11 12 32 56 45]
Array List2 : [77 98 87 95 46]
Concatenation Array : [11 12 32 56 45 77 98 87 95 46]
Sorted Array : [11 12 32 45 46 56 77 87 95 98]


### Questions 3: Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
import numpy as np
arr = np.array([1,3,2,4,5,6,7,9,8,2,1,5])

arr1=arr.reshape(4,3)
print("Array List :",'\n',arr1)

print("Dimensions of Array Is :", arr1.ndim)
print("Shape Of Array Is : ", arr1.shape)
print("Size Of Array Is :", arr1.size)

Array List : 
 [[1 3 2]
 [4 5 6]
 [7 9 8]
 [2 1 5]]
Dimensions of Array Is : 2
Shape Of Array Is :  (4, 3)
Size Of Array Is : 12


### Questions 4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet 
>Hint: np.newaxis, np.expand_dims 

In [4]:
import numpy as np

arr = np.arange(10)
print("Shape of Array :",arr.shape)

row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

column_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",column_arr.shape)


arr = np.arange(9)
print("\nShape of Array :",arr.shape)

row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)

column_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",column_arr.shape)

Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)

Shape of Array : (9,)

Shape of 2d Array in row major : (1, 9)

Shape of 2d Array in column major : (9, 1)


### Questions 5: Consider two square numpy arrays. Stack them vertically and horizontally. 
>Hint: Use vstack(), hstack() 

In [5]:
import numpy as np

arr_1 = np.array([12, 24, 49, 6, 15])
arr_2 = np.array([3, 55, 6, 8, 111])

print("Horizontal Append :", np.hstack((arr_1, arr_2)))
print("Vertical Append :\n", np.vstack((arr_1, arr_2)))

Horizontal Append : [ 12  24  49   6  15   3  55   6   8 111]
Vertical Append :
 [[ 12  24  49   6  15]
 [  3  55   6   8 111]]


### Questions 6: How to get unique items and counts of unique items? 

In [6]:
import numpy as np
Array = np.array( [1,10,20,1,2,20,2,30,3,50,40,4,45,22,6,8] )
print("Array:")
print(Array ,"\n")
unique_elements, counts_elements = np.unique(Array, return_counts=True)
print("Unique items and counts for unique items array:")
print(np.asarray((unique_elements, counts_elements)))

Array:
[ 1 10 20  1  2 20  2 30  3 50 40  4 45 22  6  8] 

Unique items and counts for unique items array:
[[ 1  2  3  4  6  8 10 20 22 30 40 45 50]
 [ 2  2  1  1  1  1  1  2  1  1  1  1  1]]
